# Use the official Golang image as the builder
FROM golang:1.13 as builder

# Set the working directory to /app
WORKDIR /app

# Copy the Go source code to the container
COPY invoke.go ./

# Build the Go application
RUN CGO_ENABLED=0 GOOS=linux go build -v -o server

# Use the official dbt-snowflake image
FROM ghcr.io/dbt-labs/dbt-snowflake:1.7.1

# Switch to root user for copying files
USER root

# Set the working directory to /dbt
WORKDIR /dbt

# Copy the compiled Go binary from the builder stage
COPY --from=builder /app/server ./

# Copy other necessary files
COPY script.sh ./
COPY . ./

# You can uncomment the following line if you need to install a Python package
# RUN pip install elementary-data[bigquery]

# Set the entry point for the container
ENTRYPOINT ["./server"]
